-- Ticket Management API Database Schema
-- Auto-generated from IntelliJ IDEA and optimized for portability

-- Create users table
CREATE TABLE IF NOT EXISTS users (
                                     id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     created_at    TIMESTAMP(6) NOT NULL,
                                     email         VARCHAR(100) NOT NULL UNIQUE,
                                     password_hash VARCHAR(255) NOT NULL,
                                     role          VARCHAR(255) NOT NULL
                                         CONSTRAINT users_role_check
                                             CHECK (role IN ('ADMIN', 'DEVELOPER')),
                                     updated_at    TIMESTAMP(6) NOT NULL,
                                     username      VARCHAR(50) NOT NULL UNIQUE
);

-- Create tickets table
CREATE TABLE IF NOT EXISTS tickets (
                                       id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       created_at  TIMESTAMP(6),
                                       description TEXT,
                                       priority    VARCHAR(255) NOT NULL
                                           CONSTRAINT tickets_priority_check
                                               CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'URGENT')),
                                       status      VARCHAR(255) NOT NULL
                                           CONSTRAINT tickets_status_check
                                               CHECK (status IN ('TODO', 'IN_PROGRESS', 'DONE')),
                                       title       VARCHAR(255) NOT NULL,
                                       updated_at  TIMESTAMP(6),
                                       assignee_id BIGINT
                                           CONSTRAINT fk_tickets_assignee
                                               REFERENCES users(id) ON DELETE SET NULL,
                                       reporter_id BIGINT NOT NULL
                                           CONSTRAINT fk_tickets_reporter
                                               REFERENCES users(id) ON DELETE CASCADE
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_tickets_status ON tickets(status);
CREATE INDEX IF NOT EXISTS idx_tickets_priority ON tickets(priority);
CREATE INDEX IF NOT EXISTS idx_tickets_assignee ON tickets(assignee_id);
CREATE INDEX IF NOT EXISTS idx_tickets_reporter ON tickets(reporter_id);
CREATE INDEX IF NOT EXISTS idx_tickets_created_at ON tickets(created_at);